# Generated by Django 2.2.4 on 2019-08-01 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('draft', models.TextField()),
                ('published_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
